landed_cost:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'lcuser') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'lcpassword') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('PIPELINE_DB_NAME', 'landed_cost_db') }}"
      schema: public
      threads: 4
