landed_cost:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'postgres') }}"
      user: "{{ env_var('POSTGRES_USER', 'landed_cost_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'landed_cost_password') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('PIPELINE_DB_NAME', 'landed_cost_db') }}"
      schema: public
      threads: 4
